import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
await import('../app/core.js');
const C=globalThis.Invictus;
test('fictional demo validates and has six separate identities',()=>assert.equal(C.validate(C.demo()).members.length,6));
test('unknown file version is rejected',()=>assert.throws(()=>C.validate({...C.demo(),schemaVersion:2})));
test('duplicate IDs are rejected',()=>{const d=C.demo();d.members[1].id=d.members[0].id;assert.throws(()=>C.validate(d),/Duplicate/);});
test('duplicate MMH numbers are rejected',()=>{const d=C.demo();d.members[0].mmh='EXAMPLE';d.members[1].mmh='EXAMPLE';assert.throws(()=>C.validate(d),/MMH/);});
test('actions cannot point at absent people',()=>{const d=C.demo();d.actions[0].memberId='absent';assert.throws(()=>C.validate(d),/missing/);});
test('completion requires a reference',()=>{const d=C.demo();d.actions[0].state='done';assert.throws(()=>C.validate(d),/reference/);});
test('completed action with evidence is accepted',()=>{const d=C.demo();d.actions[0].state='done';d.actions[0].reference='Checked source receipt';assert.equal(C.validate(d).actions[0].state,'done');});
test('unknown owner rejected',()=>{const d=C.demo();d.actions[0].owner='Anyone';assert.throws(()=>C.validate(d),/owner/);});
test('money stored as integer cents and unknown is not zero',()=>{assert.equal(C.amount('600.01'),60001);assert.equal(C.amount(''),null);assert.equal(C.amount('-25.50'),-2550);assert.throws(()=>C.amount('4.567'));assert.throws(()=>C.amount('Infinity'));});
test('impossible calendar date rejected',()=>assert.throws(()=>C.date('2026-02-30'),/calendar/));
test('valid leap date retained',()=>assert.equal(C.date('2024-02-29'),'2024-02-29'));
test('alias and invoice search work',()=>{assert.equal(C.filterMembers(C.demo(),'Ben').length,1);assert.equal(C.filterMembers(C.demo(),'DEMO-006')[0].name,'Frederick Demo');});
test('non-members do not join current roll through payment',()=>{const d=C.demo();d.members[0].memberStatus='non-member';assert.equal(C.isCurrent(d.members[0]),false);});
test('missing-KOL filter does not confuse a closed record',()=>{const d=C.demo();d.members[0].kolStatus='closed';assert.equal(C.filterMembers(d,'','missing').length,1);});
test('settlement posting is not payment chasing',()=>assert.equal(C.filterMembers(C.demo(),'','chase').length,1));
test('paid but missing registration remains a red flag',()=>assert.equal(C.isRedFlag(C.demo().members[1]),true));
test('proposed cessation is not counted current',()=>{const m=C.demo().members[0];m.memberStatus='cessation-pending';assert.equal(C.isCurrent(m),false);assert.equal(C.isDeparture(m),true);});
test('summary is computed from records, not a cached constant',()=>{const d=C.demo();assert.equal(C.summary(d).gp,920);d.members[2].gpPence=1840;assert.equal(C.summary(d).gp,1840);});
test('CSV formula injection is neutralised',()=>{const d=C.demo();d.members[0].name='=1+2';assert.match(C.csv(d),/"'=1\+2"/);});
test('untrusted display text is escaped',()=>assert.equal(C.escape('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;'));
test('raw prototype-like properties cannot enter the normalised record',()=>{const d=C.demo();d.members[0].constructor='bad';assert.equal(Object.hasOwn(C.validate(d).members[0],'constructor'),false);});
test('encrypted file round-trip preserves full working record',async()=>{const d=C.demo(),v=await C.encrypt(d,'a very long test passphrase');assert.equal(v.iterations,600000);assert.deepEqual(await C.decrypt(v,'a very long test passphrase'),d);assert.ok(!JSON.stringify(v).includes('Benedict'));});
test('wrong passphrase is rejected',async()=>{const v=await C.encrypt(C.demo(),'a very long test passphrase');await assert.rejects(C.decrypt(v,'the wrong passphrase'),/incorrect/);});
test('altered ciphertext is rejected',async()=>{const v=await C.encrypt(C.demo(),'a very long test passphrase');v.ciphertext=(v.ciphertext[0]==='A'?'B':'A')+v.ciphertext.slice(1);await assert.rejects(C.decrypt(v,'a very long test passphrase'),/incorrect/);});
test('every encrypted export receives fresh salt and IV',async()=>{const d=C.demo();const [a,b]=await Promise.all([C.encrypt(d,'a very long test passphrase'),C.encrypt(d,'a very long test passphrase')]);assert.notEqual(a.salt,b.salt);assert.notEqual(a.iv,b.iv);});
test('short export passphrases are rejected',async()=>await assert.rejects(C.encrypt(C.demo(),'short'),/12/));
test('unsafe KDF parameters are rejected before work begins',async()=>await assert.rejects(C.decrypt({format:'invictus-vault',version:1,kdf:'PBKDF2-SHA256',cipher:'AES-256-GCM',iterations:999999999},'password'),/Unsupported/));
test('UI contains no network request code',async()=>{const ui=await readFile(new URL('../app/ui.js',import.meta.url),'utf8');assert.doesNotMatch(ui,/\bfetch\s*\(|XMLHttpRequest|WebSocket|sendBeacon/);});
