import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFile } from 'node:fs/promises';
import worker from '../server/worker.mjs';
const C=globalThis.Invictus;
const schema=await readFile(new URL('../migrations/0001_online.sql',import.meta.url),'utf8');
const origin='https://register.example.workers.dev';
const issuer='https://synthetic-tests.cloudflareaccess.com';
const kp=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const jwk={...await crypto.subtle.exportKey('jwk',kp.publicKey),kid:'synthetic-key',alg:'RS256'};
const b64=value=>Buffer.from(typeof value==='string'?value:JSON.stringify(value)).toString('base64url');
async function token(email='admin@example.invalid',changes={},header={}){
  const now=Math.floor(Date.now()/1000),parts=[b64({alg:'RS256',kid:jwk.kid,...header}),b64({sub:'synthetic-subject',iss:issuer,aud:['test-audience'],iat:now,exp:now+600,email,...changes})];
  return parts.join('.')+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',kp.privateKey,new TextEncoder().encode(parts.join('.')))).toString('base64url');
}
class D1 {
  constructor(){this.db=new DatabaseSync(':memory:');this.db.exec(schema);}
  prepare(sql){const db=this.db;const statement=(args=[])=>({bind:(...p)=>statement(p),first:async()=>db.prepare(sql).get(...args)||null,all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>db.prepare(sql).run(...args)});return statement();}
}
const roles={'admin@example.invalid':'admin','registrar@example.invalid':'registrar','treasurer@example.invalid':'treasurer','viewer@example.invalid':'viewer'};
function env(){return {DB:new D1(),ASSETS:{fetch:async()=>new Response('synthetic shell')},ACCESS_ISSUER:issuer,ACCESS_AUD:'test-audience',OFFICER_ROLES:JSON.stringify(roles)};}
function req(path,method='GET',payload=null,t='',version=1,extras={}){return new Request(origin+path,{method,headers:{...(t?{'Cf-Access-Jwt-Assertion':t}:{}),...(payload?{'Content-Type':'application/json','Origin':origin,'X-Invictus-Request':'1','If-Match':`"${version}"`}:{}),...extras},...(payload?{body:JSON.stringify(payload)}:{})});}
const admin=await token(),registrar=await token('registrar@example.invalid'),treasurer=await token('treasurer@example.invalid'),viewer=await token('viewer@example.invalid');
const data=()=>C.demo();
async function seed(en,d=data()){const response=await worker.fetch(req('/api/register','POST',{register:d,reference:'Synthetic source reviewed'},admin,0,{'If-None-Match':'*'}),en);assert.equal(response.status,201,await response.clone().text());return response.json();}
const originalFetch=globalThis.fetch;
globalThis.fetch=async url=>{assert.equal(String(url),issuer+'/cdn-cgi/access/certs');return Response.json({keys:[jwk]});};
process.on('exit',()=>{globalThis.fetch=originalFetch;});

test('unconfigured deployment fails closed for page and API',async()=>{for(const path of ['/','/api/register'])assert.equal((await worker.fetch(req(path),{})).status,503);});
test('missing, forged and expired authentication rejected',async()=>{const en=env();for(const t of ['', 'a.b.c',await token(undefined,{exp:1}),await token(undefined,{aud:['wrong']}),await token(undefined,{iss:'https://other.cloudflareaccess.com'}),await token(undefined,{}, {alg:'none'})])assert.equal((await worker.fetch(req('/api/register','GET',null,t),en)).status,401);});
test('signature tampering rejected',async()=>{const p=admin.split('.');p[1]=b64({sub:'x',email:'admin@example.invalid',iss:issuer,aud:['test-audience'],iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+1000});assert.equal((await worker.fetch(req('/api/register','GET',null,p.join('.')),env())).status,401);});
test('correct login but unknown account rejected',async()=>{assert.equal((await worker.fetch(req('/','GET',null,await token('unknown@example.invalid')),env())).status,403);});
test('identity headers without a signed assertion cannot bypass sign-in',async()=>{assert.equal((await worker.fetch(req('/api/register','GET',null,'',1,{'Cf-Access-Authenticated-User-Email':'admin@example.invalid'}),env())).status,401);});
test('assets require authentication and private source paths cannot be served',async()=>{const en=env();assert.equal((await worker.fetch(req('/ui.js'),en)).status,401);assert.equal((await worker.fetch(req('/ui.js','GET',null,admin),en)).status,200);for(const path of ['/private/register.json','/server/auth.mjs','/.env'])assert.equal((await worker.fetch(req(path,'GET',null,admin),en)).status,404);});
test('empty online state is explicit and contains no demo data',async()=>{const r=await worker.fetch(req('/api/register','GET',null,admin),env());assert.deepEqual(await r.json(),{register:null,version:0,savedAt:null});assert.match(r.headers.get('cache-control'),/no-store/);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);});
test('seed once and reopen from a second officer session',async()=>{const en=env(),s=await seed(en);const r=await worker.fetch(req('/api/register','GET',null,viewer),en);assert.equal((await r.json()).register.id,s.register.id);assert.equal((await worker.fetch(req('/api/register','POST',{register:data(),reference:'x'},admin,0,{'If-None-Match':'*'}),en)).status,409);});
test('viewer cannot initialise, change a record or inspect recovery snapshots',async()=>{const en=env();await seed(en);assert.equal((await worker.fetch(req('/api/members/DEMO0','PATCH',{changes:{notes:'bad'},reason:'x'},viewer),en)).status,403);assert.equal((await worker.fetch(req('/api/backups','GET',null,viewer),en)).status,403);});
test('cross-origin writes rejected without changing database',async()=>{const en=env();await seed(en);const p={changes:{notes:'bad'},reason:'x'};for(const h of [{Origin:'https://evil.invalid'},{Origin:''},{'X-Invictus-Request':''}])assert.equal((await worker.fetch(req('/api/members/DEMO0','PATCH',p,admin,1,h),en)).status,403);assert.equal((await en.DB.prepare('SELECT version FROM register_state').first()).version,1);});
test('member changes save with verified actor, server timestamp, backup and source preserved',async()=>{const en=env();const d=data();d.members[0].original='original evidence';d.members[0].balance=null;await seed(en,d);const r=await worker.fetch(req('/api/members/DEMO0','PATCH',{changes:{notes:'reviewed'},reason:'synthetic note',actor:'forged'},registrar),en);assert.equal(r.status,200);const b=await r.json();assert.equal(b.version,2);assert.equal(b.register.members[0].original,'original evidence');assert.equal(b.register.members[0].balance,null);assert.equal(b.register.history.at(-1).actor,'registrar@example.invalid');assert.equal((await en.DB.prepare('SELECT COUNT(*) AS n FROM register_audit').first()).n,2);assert.equal((await en.DB.prepare('SELECT COUNT(*) AS n FROM register_backups').first()).n,2);});
test('protected source fields, unsupported fields and financial cross-role changes rejected',async()=>{const en=env();await seed(en);for(const [changes,t] of [[{original:'rewrite'},admin],[{ledgerBalance:0},admin],[{balance:0},registrar],[{memberStatus:'ceased'},treasurer],[{isAdmin:true},admin]])assert.equal((await worker.fetch(req('/api/members/DEMO0','PATCH',{changes,reason:'x'},t),en)).status,403);});
test('treasurer may update financial summary but promise is not a payment',async()=>{const en=env();await seed(en);const r=await worker.fetch(req('/api/members/DEMO0','PATCH',{changes:{financeStatus:'promised',balance:15000},reason:'Promise only'},treasurer),en);assert.equal(r.status,200);const m=(await r.json()).register.members[0];assert.equal(m.financeStatus,'promised');assert.equal(m.balance,15000);assert.equal(m.memberStatus,'subscribing');});
test('invalid money, date and duplicate MMH fail without writes',async()=>{const en=env();const d=data();d.members[1].mmh='TEST-MEMBER';await seed(en,d);for(const changes of [{balance:1.5},{effectiveDate:'2026-02-31'},{mmh:'TEST-MEMBER'},{name:''}])assert.equal((await worker.fetch(req('/api/members/DEMO0','PATCH',{changes,reason:'test'},admin),en)).status,422);assert.equal((await en.DB.prepare('SELECT version FROM register_state').first()).version,1);});
test('missing version precondition and stale save rejected',async()=>{const en=env();await seed(en);const r=req('/api/members/DEMO0','PATCH',{changes:{notes:'stale'},reason:'x'},admin);r.headers.delete('If-Match');assert.equal((await worker.fetch(r,en)).status,428);assert.equal((await worker.fetch(req('/api/members/DEMO0','PATCH',{changes:{notes:'stale'},reason:'x'},admin,0),en)).status,409);});
test('concurrent editors cannot overwrite one another',async()=>{const en=env();await seed(en);const out=await Promise.all(['one','two'].map(notes=>worker.fetch(req('/api/members/DEMO0','PATCH',{changes:{notes},reason:'Concurrent test'},admin),en)));assert.deepEqual(out.map(r=>r.status).sort(),[200,409]);assert.equal((await en.DB.prepare('SELECT COUNT(*) AS n FROM register_audit').first()).n,2);});
test('action completion requires evidence and cannot change KOL',async()=>{const en=env();await seed(en);assert.equal((await worker.fetch(req('/api/actions/TASK1','PATCH',{state:'done',reference:''},registrar),en)).status,422);const r=await worker.fetch(req('/api/actions/TASK1','PATCH',{state:'done',reference:'synthetic external reference'},registrar),en);assert.equal(r.status,200);assert.equal((await r.json()).register.members[1].kolStatus,'missing');});
test('action ownership enforced by server',async()=>{const en=env();await seed(en);assert.equal((await worker.fetch(req('/api/actions/TASK2','PATCH',{state:'done',reference:'x'},registrar),en)).status,403);assert.equal((await worker.fetch(req('/api/actions','POST',{memberId:'DEMO0',owner:'Registrar',title:'x'},treasurer),en)).status,403);});
test('orphan follow-ups rejected, new people start unresolved',async()=>{const en=env();await seed(en);assert.equal((await worker.fetch(req('/api/actions','POST',{memberId:'missing',owner:'Registrar',title:'x'},admin),en)).status,422);const r=await worker.fetch(req('/api/members','POST',{name:'New Example',reason:'Enquiry'},registrar),en);assert.equal(r.status,200);assert.equal((await r.json()).register.members.at(-1).memberStatus,'review');});
test('audit cannot be rewritten through API; backup contains prior values',async()=>{const en=env();await seed(en);await worker.fetch(req('/api/members/DEMO0','PATCH',{changes:{notes:'new'},reason:'x'},admin),en);const r=await worker.fetch(req('/api/backups/1','GET',null,admin),en);assert.equal((await r.json()).members[0].notes,'');assert.equal((await worker.fetch(req('/api/audit','PATCH',{events:[]},admin,2),en)).status,404);});
test('oversize streamed request rejected',async()=>{const en=env();await seed(en);assert.equal((await worker.fetch(req('/api/members/DEMO0','PATCH',{changes:{notes:'x'.repeat(1500001)},reason:'x'},admin),en)).status,413);});
test('audit trigger failure rolls back data change',async()=>{const en=env();await seed(en);en.DB.db.exec("CREATE TRIGGER fail_audit BEFORE INSERT ON register_audit WHEN NEW.version=2 BEGIN SELECT RAISE(ABORT,'simulated'); END;");assert.equal((await worker.fetch(req('/api/members/DEMO0','PATCH',{changes:{notes:'must rollback'},reason:'x'},admin),en)).status,500);const row=await en.DB.prepare('SELECT * FROM register_state').first();assert.equal(row.version,1);assert.equal(JSON.parse(row.data).members[0].notes,'');});
test('60 recovery snapshots retained while audit retains every revision',async()=>{const en=env();await seed(en);for(let v=1;v<=62;v++){const r=await worker.fetch(req('/api/members/DEMO0','PATCH',{changes:{notes:'revision '+v},reason:'synthetic test'},admin,v),en);assert.equal(r.status,200);}assert.equal((await en.DB.prepare('SELECT COUNT(*) AS n FROM register_backups').first()).n,60);assert.equal((await en.DB.prepare('SELECT COUNT(*) AS n FROM register_audit').first()).n,63);});
