/* Invictus Register: local-only data, validation and encrypted-file functions. */
(function (root) {
  'use strict';
  const STATUS = {subscribing:'Subscribing',country:'Country',honorary:'Honorary',resigned:'Resigned','cessation-pending':'Cessation pending',ceased:'Ceased',deceased:'Deceased',applicant:'Applicant','non-member':'Not a member',review:'Status to verify'};
  const KOL = {registered:'On KOL',closed:'Closed on KOL',missing:'Missing from KOL',correction:'Correction pending',verify:'Check KOL','not-applicable':'Not applicable'};
  const FINANCE = {settled:'Settled',posting:'Paid · posting pending',chase:'Follow up payment',promised:'Payment promised',reconcile:'Reconcile first',unknown:'Account unknown','not-applicable':'Not applicable'};
  const BASIS = {source:'Source record',confirmed:'User confirmed',proposed:'Proposed',verified:'Verified',unresolved:'Unresolved'};
  const TASK = {open:'Open',progress:'In progress',waiting:'Waiting',done:'Done'};
  const OWNERS = ['Registrar','Treasurer','Preceptor'];
  const FORMAT = 'invictus-register';
  const LIMIT = 5 * 1024 * 1024;
  const ITERATIONS = 600000;
  const assert = (ok, message) => { if (!ok) throw new Error(message); };
  const str = (v, max=10000) => { assert(typeof v === 'string' && v.length <= max, 'Invalid or oversized text field.'); return v; };
  const date = (s) => { if (s === '') return s; assert(typeof s === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(s), 'Use dates in YYYY-MM-DD format.'); const d=new Date(s+'T12:00:00Z'); assert(Number.isFinite(+d) && d.toISOString().slice(0,10)===s, 'Invalid calendar date.'); return s; };
  const choice = (v, choices) => { assert(Object.hasOwn(choices,v), 'Unrecognised status: '+String(v).slice(0,50)); return v; };
  const money = (v, nullable=true, signed=true) => { assert((nullable && v===null) || (Number.isSafeInteger(v) && Math.abs(v)<=1000000000 && (signed || v>=0)), 'Invalid money value. Store integer cents/pence, not decimals.'); return v; };
  const uid = () => { if (root.crypto.randomUUID) return root.crypto.randomUUID(); const a=root.crypto.getRandomValues(new Uint8Array(16)); a[6]=(a[6]&15)|64; a[8]=(a[8]&63)|128; const h=Array.from(a,n=>n.toString(16).padStart(2,'0')).join(''); return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20); };
  function member(m) {
    assert(m && typeof m === 'object' && !Array.isArray(m),'Invalid member record.');
    const out={id:str(m.id,100),name:str(m.name,200).trim(),aliases:[],mmh:str(m.mmh||'',40),memberStatus:choice(m.memberStatus,STATUS),basis:choice(m.basis||'unresolved',BASIS),effectiveDate:date(m.effectiveDate||''),admissionDate:date(m.admissionDate||''),admissionRoute:str(m.admissionRoute||'',120),kolStatus:choice(m.kolStatus||'verify',KOL),kolAsOf:date(m.kolAsOf||''),financeStatus:choice(m.financeStatus||'unknown',FINANCE),balance:money(m.balance===undefined?null:m.balance),ledgerBalance:money(m.ledgerBalance===undefined?null:m.ledgerBalance),invoice:str(m.invoice||'',100),gpPence:money(m.gpPence||0,false,false),gpBasis:str(m.gpBasis||''),statusNote:str(m.statusNote||''),financeNote:str(m.financeNote||''),notes:str(m.notes||''),sources:[],original:str(m.original||'',30000)};
    assert(out.id && out.name,'Every record requires an ID and a name.');
    assert(Array.isArray(m.aliases||[]) && (m.aliases||[]).length<=30,'Too many aliases.');out.aliases=(m.aliases||[]).map(x=>str(x,200));
    assert(Array.isArray(m.sources||[]) && (m.sources||[]).length<=60,'Too many source references.');out.sources=(m.sources||[]).map(x=>str(x,2000));
    return out;
  }
  function validate(raw) {
    assert(raw && raw.format===FORMAT && raw.schemaVersion===1,'This is not an Invictus Register v1 file. Choose a register JSON or encrypted .invictus file.');
    assert(Array.isArray(raw.members) && raw.members.length<=2000,'Invalid member list (maximum 2,000 records).');
    assert(Array.isArray(raw.actions||[]) && (raw.actions||[]).length<=15000,'Invalid action list.');
    assert(Array.isArray(raw.history||[]) && (raw.history||[]).length<=20000,'Invalid change history.');
    const out={format:FORMAT,schemaVersion:1,id:str(raw.id,100),title:str(raw.title||'Invictus Register',200),asOf:date(raw.asOf||''),revision:raw.revision||0,notice:str(raw.notice||''),members:raw.members.map(member),actions:[],history:[]};
    assert(out.id && Number.isSafeInteger(out.revision) && out.revision>=0,'Invalid register identity or revision.');
    const ids=new Set(),mmhs=new Set(),taskIds=new Set(),eventIds=new Set();
    for(const m of out.members){assert(!ids.has(m.id),'Duplicate record ID: '+m.id);ids.add(m.id);if(m.mmh){assert(!mmhs.has(m.mmh),'Duplicate MMH number: '+m.mmh);mmhs.add(m.mmh);}}
    out.actions=(raw.actions||[]).map(a=>{assert(a&&ids.has(a.memberId),'An action points to a missing member.');assert(OWNERS.includes(a.owner),'Invalid action owner.');const t={id:str(a.id,100),memberId:a.memberId,title:str(a.title,3000),owner:a.owner,state:choice(a.state,TASK),priority:choice(a.priority||'normal',{high:1,normal:1}),due:date(a.due||''),reference:str(a.reference||'',3000)};assert(t.id&&!taskIds.has(t.id),'Duplicate or empty action ID.');taskIds.add(t.id);assert(t.state!=='done'||t.reference.trim(),'Completed actions require a completion reference.');return t;});
    out.history=(raw.history||[]).map(h=>{const e={id:str(h.id,100),at:str(h.at,60),actor:str(h.actor,120),memberId:str(h.memberId||'',100),summary:str(h.summary,10000),reference:str(h.reference||'',3000)};assert(e.id&&!eventIds.has(e.id),'Duplicate or empty event ID.');eventIds.add(e.id);assert(!e.memberId||ids.has(e.memberId),'A history event points to a missing member.');return e;});
    return out;
  }
  const normalise = v => String(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const isCurrent = m => ['subscribing','country','honorary'].includes(m.memberStatus);
  const isDeparture = m => ['resigned','ceased','cessation-pending','deceased'].includes(m.memberStatus);
  const isRedFlag = m => ['missing','correction'].includes(m.kolStatus)||['review','cessation-pending'].includes(m.memberStatus)||m.basis==='unresolved';
  function matches(m, query) { const hay=normalise([m.name,m.mmh,m.id,m.invoice,...m.aliases,STATUS[m.memberStatus],KOL[m.kolStatus],FINANCE[m.financeStatus]].join(' '));return normalise(query).trim().split(/\s+/).every(s=>hay.includes(s)); }
  function filterMembers(data, query='', filter='all') {return data.members.filter(m=>matches(m,query)).filter(m=>filter==='current'?isCurrent(m):filter==='missing'?m.kolStatus==='missing':filter==='chase'?['chase','promised'].includes(m.financeStatus):filter==='departures'?isDeparture(m):filter==='review'?isRedFlag(m):true).sort((a,b)=>a.name.localeCompare(b.name));}
  function summary(data){return {records:data.members.length,current:data.members.filter(isCurrent).length,registrar:data.actions.filter(a=>a.state!=='done'&&a.owner==='Registrar').length,treasurer:data.actions.filter(a=>a.state!=='done'&&a.owner==='Treasurer').length,gp:data.members.reduce((n,m)=>n+m.gpPence,0),redFlags:data.members.filter(isRedFlag).length};}
  function amount(text) {if(String(text).trim()==='')return null;assert(/^-?\d{1,8}(\.\d{1,2})?$/.test(String(text).trim()),'Enter a money amount with at most two decimals.');const n=Math.round(Number(text)*100);return money(n);}
  const fmtMoney = (n,currency='SGD') => n===null?'Not established':new Intl.NumberFormat('en-SG',{style:'currency',currency,currencyDisplay:'narrowSymbol'}).format(n/100);
  const fmtDate = s => s?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(s+'T12:00:00Z')):'Not established';
  const escape = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const csvCell = value => {let s=String(value??'');if(/^[\s]*[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};
  function csv(data, list=data.members){const rows=[['Name','MMH','Membership','Basis','Effective date','KOL','Account status','Working balance SGD','Original ledger SGD','Invoice','Proposed GP cost GBP','Notes']];for(const m of list)rows.push([m.name,m.mmh,STATUS[m.memberStatus],BASIS[m.basis],m.effectiveDate,KOL[m.kolStatus],FINANCE[m.financeStatus],m.balance===null?'':(m.balance/100).toFixed(2),m.ledgerBalance===null?'':(m.ledgerBalance/100).toFixed(2),m.invoice,(m.gpPence/100).toFixed(2),[m.statusNote,m.financeNote,m.notes].filter(Boolean).join(' | ')]);return '\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n');}
  const b64 = buf => {const a=new Uint8Array(buf);let s='';for(let i=0;i<a.length;i+=8192)s+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(s);};
  const unb64 = s => {str(s,LIMIT*2);assert(/^[A-Za-z0-9+/]*={0,2}$/.test(s),'Invalid encrypted file encoding.');return Uint8Array.from(atob(s),c=>c.charCodeAt(0));};
  async function key(password,salt,iterations){assert(root.crypto?.subtle,'Encrypted saving is unavailable here. Open in current Edge/Chrome locally or on HTTPS.');const k=await root.crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return root.crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},k,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
  async function encrypt(data,password){assert(typeof password==='string'&&password.length>=12&&password.length<=256,'Use a passphrase of 12–256 characters.');const plain=JSON.stringify(validate(data));assert(plain.length<LIMIT,'Register exceeds the 5 MB export limit.');const salt=root.crypto.getRandomValues(new Uint8Array(16)),iv=root.crypto.getRandomValues(new Uint8Array(12));const k=await key(password,salt,ITERATIONS);const ciphertext=await root.crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode('invictus-vault/v1')},k,new TextEncoder().encode(plain));return {format:'invictus-vault',version:1,kdf:'PBKDF2-SHA256',iterations:ITERATIONS,cipher:'AES-256-GCM',salt:b64(salt),iv:b64(iv),ciphertext:b64(ciphertext)};}
  async function decrypt(v,password){assert(v?.format==='invictus-vault'&&v.version===1&&v.kdf==='PBKDF2-SHA256'&&v.cipher==='AES-256-GCM'&&v.iterations===ITERATIONS,'Unsupported encrypted-file format.');assert(typeof password==='string'&&password.length<=256,'Invalid passphrase.');const salt=unb64(v.salt),iv=unb64(v.iv),ciphertext=unb64(v.ciphertext);assert(salt.length===16&&iv.length===12&&ciphertext.length>=16&&ciphertext.length<LIMIT,'Invalid encrypted-file length.');const k=await key(password,salt,v.iterations);let plain;try{plain=await root.crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode('invictus-vault/v1')},k,ciphertext);}catch{throw new Error('The passphrase is incorrect or this encrypted file has been altered. Your current register has not changed.');}return validate(JSON.parse(new TextDecoder().decode(plain)));}
  function blank(){return {format:FORMAT,schemaVersion:1,id:uid(),title:'Invictus Preceptory & Priory No. 724',asOf:new Date().toISOString().slice(0,10),revision:0,notice:'Working register. Check supporting records before certifying membership or accounts.',members:[],actions:[],history:[]};}
  function demo(){const d=blank();d.title='Demonstration · fictional records';d.notice='DEMONSTRATION DATA ONLY. No real member information is included.';const examples=[['Arthur Example','subscribing','confirmed','registered','settled',0],['Benedict Sample','subscribing','source','missing','posting',0],['Christopher Demo','resigned','confirmed','correction','reconcile',null],['David Example','honorary','source','registered','not-applicable',null],['Edward Sample','review','unresolved','verify','unknown',null],['Frederick Demo','subscribing','confirmed','registered','promised',15000]];d.members=examples.map((x,i)=>member({id:'DEMO'+i,name:x[0],memberStatus:x[1],basis:x[2],kolStatus:x[3],financeStatus:x[4],balance:x[5],ledgerBalance:i===1?50000:x[5],aliases:i===1?['Ben']:[],mmh:'',invoice:i===5?'DEMO-006':'',gpPence:i===2?920:0,statusNote:'Fictional example. Replace this demonstration with your private register.',financeNote:i===1?'Payment reported. Ledger posting remains a separate task.':''}));d.actions=[{id:'TASK1',memberId:'DEMO1',title:'Complete registration and verify the external record',owner:'Registrar',state:'open',priority:'high',due:'',reference:''},{id:'TASK2',memberId:'DEMO1',title:'Post and allocate the payment; do not chase again',owner:'Treasurer',state:'open',priority:'normal',due:'',reference:''},{id:'TASK3',memberId:'DEMO5',title:'Resend the invoice and follow up the promised payment',owner:'Treasurer',state:'open',priority:'normal',due:'',reference:''},{id:'TASK4',memberId:'DEMO2',title:'Correct the external membership end date',owner:'Registrar',state:'waiting',priority:'high',due:'',reference:''}];return validate(d);}
  root.Invictus={STATUS,KOL,FINANCE,BASIS,TASK,OWNERS,LIMIT,uid,member,validate,date,amount,fmtMoney,fmtDate,escape,csv,isCurrent,isDeparture,isRedFlag,matches,filterMembers,summary,encrypt,decrypt,blank,demo};
})(globalThis);
